# Generated by Django 2.1.7 on 2019-08-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': '친구 요청 상태', 'verbose_name_plural': '친구 요청 상태 목록'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
