# Generated by Django 2.1.7 on 2019-02-22 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assented_at', models.DateTimeField(blank=True, null=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_user', to=settings.AUTH_USER_MODEL)),
                ('response_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_response_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='userProfile_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
