# Generated by Django 2.1.7 on 2019-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190222_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '사용 중인 이메일입니다'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '사용 중인 닉네임입니다'}, max_length=30, unique=True),
        ),
    ]
